name: studiop4
favicon: null
layout_spectrum: 1
typography_spectrum: 0.745353524107486
title: Création Graphique au cœur du Périgord Noir
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eff8fd'
    - '#006ab3'
    - '#646567'
    - '#86898c'
    - '#93c0de'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
